export const CATEGORY_SHORT_DESCRIPTIONS: Record<string, string> = {
  'AI Writing': 'Generate, edit, and optimize content — from blog posts to marketing copy.',
  'AI Coding': 'AI coding assistants, IDEs, and developer tools that accelerate software development.',
  'AI Design': 'Image generation, graphic design, logo creation, and visual content tools.',
  'AI Video': 'Video generation, editing, and avatar tools for creators and marketers.',
  'AI Audio': 'Audio tools including text-to-speech, voice cloning, transcription, and music.',
  'AI Automation': 'No-code and low-code platforms to streamline workflows across SaaS tools.',
  'AI Marketing': 'Marketing tools for SEO, ads, campaign optimization, and brand content.',
  'AI Analytics': 'Analytics and business intelligence tools for data-driven decision making.',
  'AI Productivity': 'Productivity tools including meeting assistants, email tools, and task management.',
  'AI Research': 'Research tools for summarization, literature review, and knowledge discovery.',
  'AI Sales': 'Sales tools for lead generation, outreach automation, and CRM enrichment.',
  'AI Customer Support': 'Chatbots and helpdesk tools that automate and improve customer support.',
  'AI HR': 'HR tools for recruitment, candidate screening, and onboarding automation.',
  'AI Education': 'Education and tutoring tools for personalized learning experiences.',
  'AI Legal': 'Legal tools for contract review, compliance, and document automation.',
  'AI Finance': 'Finance tools for accounting, invoicing, expense tracking, and reporting.',
  'AI Healthcare': 'Healthcare tools for clinical documentation, patient management, and diagnostics.',
  'AI Translation': 'Translation and localization tools for multilingual content.',
  'AI Image': 'Image editing, enhancement, and generation tools.',
  'AI Chat': 'Chatbots and conversational AI platforms.',
  'AI Security': 'Cybersecurity tools for threat detection, vulnerability scanning, and fraud prevention.',
  'AI Data Extraction': 'Web scraping and data extraction tools.',
  'AI Presentation': 'Presentation and slide generation tools.',
  'AI Social Media': 'Social media management, scheduling, and content generation tools.',
  'AI Voice': 'Voice synthesis and voice cloning tools.',
  'AI Avatar': 'Avatar and digital human creation tools.',
  'AI Search': 'AI-powered search and information retrieval tools.',
  'AI Travel': 'Personalized travel planning, itineraries, and intelligent trip assistance.'
};

export const CATEGORY_LONG_DESCRIPTIONS: Record<string, string> = {
  'AI Writing': "Unleash your creativity and conquer the blank page with AI writing tools. In an era where content is king, crafting compelling narratives, persuasive marketing copy, and engaging blog posts is more critical than ever. AI writing assistants are your tireless co-authors, capable of brainstorming ideas, overcoming writer's block, and polishing your prose to perfection. Whether you are a seasoned author looking to accelerate your drafting process, a marketer scaling up campaign generation, or a student seeking to improve your essays, AI technology analyzes context and tone to generate text that resonates with your audience. Say goodbye to tedious editing and embrace a world where your ideas flow effortlessly into words. Explore our curated list of AI writing platforms and discover how intelligent algorithms can elevate your voice and transform your writing journey.",

  'AI Coding': "Accelerate your development cycle and write cleaner, bug-free code with AI coding tools. Software development is evolving rapidly, and AI is at the forefront of this revolution, acting as a pair programmer that never sleeps. From intelligent code completion and syntax error detection to generating entire functions from natural language prompts, AI coding assistants dramatically reduce boilerplate tasks and allow developers to focus on high-level architecture and logic. Whether you are a beginner learning your first language or a senior engineer managing complex codebases, these tools help you debug faster, understand legacy code, and deploy applications with confidence. Embrace the future of software engineering and let AI handle the syntax while you focus on the solution.",

  'AI Design': "Bring your wildest visual concepts to life with AI design tools, where imagination meets infinite possibility. Graphic design is no longer constrained by the limits of a blank canvas or traditional software proficiency. AI-powered design platforms allow you to generate stunning layouts, create custom logos, and refine color palettes with simple text descriptions or intuitive sliders. Whether you are a professional designer seeking inspiration, a startup founder building a brand identity from scratch, or a social media manager creating daily content, AI democratizes high-end aesthetics. Discover tools that intelligently remove backgrounds, upscale images without losing quality, and adapt designs across multiple formats seamlessly. Redefine your creative workflow and let AI be the brush that paints your digital masterpiece.",

  'AI Video': "Revolutionize your visual storytelling with AI video tools, turning concepts into cinematic reality in minutes. The barrier to entry for high-quality video production has been shattered by artificial intelligence. Today, you can generate entire marketing videos, explainer animations, and social media clips without needing a camera, actors, or a studio. AI video platforms offer features like text-to-video generation, automated scene editing, and intelligent b-roll selection. Whether you are a content creator looking to scale your YouTube channel or an enterprise producing training materials, these tools streamline the editing process and offer unprecedented creative freedom. Step into the director's chair and let AI handle the heavy lifting of video production.",

  'AI Audio': "Transform the soundscape of your projects with AI audio tools, where pristine audio generation is just a click away. From crystal-clear noise reduction to generating original, royalty-free music tracks, AI is changing how we interact with sound. These platforms offer breakthrough capabilities such as text-to-speech with lifelike emotional inflection, voice cloning for personalized narration, and intelligent podcast editing that automatically removes filler words. Whether you are an indie game developer needing custom sound effects, a podcaster aiming for studio-quality production, or a marketer creating localized voiceovers, AI audio tools provide the perfect sonic backdrop. Elevate your auditory experience and let intelligent algorithms mix, master, and synthesize your perfect sound.",

  'AI Automation': "Supercharge your productivity and eliminate repetitive tasks with AI automation tools. In the modern digital workplace, time is your most valuable asset, and AI automation is the ultimate time-saver. By connecting your favorite SaaS applications and utilizing intelligent triggers, these platforms can automate complex workflows, data entry, and communication processes without requiring a single line of code. Whether you are routing customer inquiries, scraping data for market research, or syncing databases, AI understands context and makes autonomous decisions to keep your operations running smoothly. Reclaim your focus for strategic, high-impact work and let AI serve as your tireless digital workforce.",

  'AI Marketing': "Elevate your brand's reach and maximize your ROI with AI marketing tools. In a crowded digital landscape, generic campaigns no longer cut through the noise. AI empowers marketers to analyze vast datasets, predict consumer behavior, and personalize messaging at an unprecedented scale. From optimizing ad spend in real-time and generating high-converting ad copy to predicting churn and segmenting audiences, AI marketing platforms provide a distinct competitive advantage. Whether you are a solo entrepreneur or a global enterprise, these intelligent tools help you deliver the right message to the right person at the exact right moment. Transform your marketing strategy from guesswork to data-driven precision.",

  'AI Analytics': "Unlock the hidden stories within your data using AI analytics tools. In today's data-rich environment, simply having numbers isn't enough; you need actionable insights. AI analytics platforms go beyond traditional dashboards by using machine learning to detect anomalies, forecast trends, and answer complex business questions in plain English. Whether you are tracking financial metrics, user engagement, or supply chain logistics, AI acts as an expert data scientist, instantly summarizing massive datasets and highlighting opportunities for growth. Stop drowning in spreadsheets and start making proactive, informed decisions with the power of intelligent data analysis.",

  'AI Productivity': "Reclaim your time and master your daily workflow with AI productivity tools. The modern workday is often fragmented by emails, meetings, and endless to-do lists. AI productivity assistants help you cut through the chaos by intelligently prioritizing tasks, drafting email responses, and summarizing lengthy documents or meeting transcripts. Whether you are a busy executive trying to achieve inbox zero or a freelancer juggling multiple projects, these tools act as your personal chief of staff, organizing your digital life and keeping you focused on what truly matters. Experience a new level of efficiency and let AI streamline your day-to-day operations.",

  'AI Research': "Accelerate your discovery process and synthesize vast amounts of information with AI research tools. Whether you are an academic conducting a literature review, a financial analyst tracking market trends, or a student writing a thesis, sifting through thousands of papers and articles is a daunting task. AI research assistants can instantly summarize complex documents, extract key data points, and identify connections across disparate sources. By acting as a tireless research partner, these tools allow you to grasp the core concepts of lengthy texts in seconds, saving you hours of reading and helping you uncover insights faster than ever before.",

  'AI Sales': "Close deals faster and build stronger customer relationships with AI sales tools. The sales landscape is highly competitive, and AI provides the edge needed to outpace the competition. From predictive lead scoring and automated outreach sequences to conversational intelligence that analyzes sales calls for coaching moments, AI platforms streamline the entire sales funnel. Whether you are an SDR prospecting for new business or a VP of Sales forecasting quarterly revenue, these tools provide actionable insights and automate administrative tasks so you can spend more time actually selling. Empower your sales team with intelligent technology and watch your conversion rates soar.",

  'AI Customer Support': "Deliver exceptional, round-the-clock service with AI customer support tools. Today's consumers expect instant resolutions, and AI enables businesses to meet those expectations without scaling massive support teams. Intelligent chatbots can instantly answer FAQs, route complex issues to the right human agent, and even process returns autonomously. Furthermore, AI helps human agents draft empathetic, accurate responses faster. Whether you are an e-commerce brand handling seasonal spikes or a SaaS company offering global support, AI ensures your customers feel heard and valued. Transform your support center into a proactive, frictionless experience.",

  'AI HR': "Modernize your workforce management and discover top talent faster with AI HR tools. Human resources is about people, and AI helps HR professionals spend less time on paperwork and more time building culture. From intelligent resume parsing and automated candidate matching to employee sentiment analysis and personalized onboarding experiences, AI platforms streamline the entire employee lifecycle. Whether you are a recruiter looking to eliminate bias in the hiring process or an HR manager seeking to improve retention, these tools provide data-driven insights to help you build a happier, more productive team.",

  'AI Education': "Personalize the learning journey and unlock every student's potential with AI education tools. The traditional one-size-fits-all approach to education is being transformed by intelligent tutoring systems. AI education platforms adapt to a learner's pace, identifying knowledge gaps and generating custom quizzes, flashcards, and explanations tailored to their specific needs. Whether you are a teacher looking to automate grading, a student seeking a 24/7 digital tutor, or a lifelong learner acquiring a new language, AI makes learning more engaging, accessible, and effective. Step into the future of interactive learning.",

  'AI Legal': "Navigate complex regulations and streamline document review with AI legal tools. The legal profession is famously document-heavy, but AI is dramatically reducing the hours spent on manual review. Intelligent legal assistants can rapidly analyze contracts, flag potential liabilities, ensure compliance, and even draft standard legal agreements. Whether you are a corporate counsel managing risk or a paralegal conducting e-discovery, these platforms provide unparalleled accuracy and speed. Empower your legal practice with technology that helps you work smarter, reduce human error, and deliver faster results for your clients.",

  'AI Finance': "Optimize your financial operations and forecast with confidence using AI finance tools. In the world of finance, accuracy and speed are paramount. AI platforms are revolutionizing accounting, expense tracking, and financial modeling by automating data entry, detecting fraudulent transactions in real-time, and generating predictive revenue forecasts. Whether you are a startup founder managing runway or a CFO analyzing global market trends, AI provides deep, actionable insights into your financial health. Move beyond manual bookkeeping and embrace intelligent financial management.",

  'AI Healthcare': "Enhance patient care and streamline clinical operations with AI healthcare tools. The healthcare industry is embracing AI to solve some of its most complex challenges. From intelligent diagnostic assistants and predictive patient monitoring to automated medical transcription and claims processing, AI is reducing administrative burnout and allowing doctors to focus on patients. Whether you are a clinician seeking a second opinion from advanced imaging algorithms or an administrator optimizing hospital workflows, AI technology is driving a new era of precision medicine and operational efficiency.",

  'AI Translation': "Break down language barriers and connect with a global audience using AI translation tools. Perfect communication is no longer limited by geography. Advanced neural machine translation models deliver highly accurate, culturally nuanced translations in real-time. Whether you are localizing a software application, translating complex legal documents, or holding a live multilingual webinar, AI platforms ensure your message is understood perfectly across borders. Expand your international reach and foster global collaboration with translation technology that speaks your language.",

  'AI Image': "Transform simple text prompts into breathtaking visuals with AI image tools. The era of generative art has arrived, allowing anyone to become a digital artist. Whether you need photorealistic stock photos for a marketing campaign, stylized illustrations for a children's book, or rapid concept art for game development, AI image generators produce stunning, high-resolution results in seconds. Beyond generation, AI image editors offer magical capabilities like intelligent object removal, background replacement, and resolution upscaling. Unleash your visual creativity without limits.",

  'AI Chat': "Engage in intelligent, context-aware conversations with AI chat tools. Conversational AI has evolved far beyond simple rule-based bots. Today's AI chat platforms utilize large language models to understand nuance, maintain context over long interactions, and provide human-like responses. Whether you are looking for a personal brainstorming partner, an intelligent companion to practice a new language, or a sophisticated bot to integrate into your customer portal, AI chat tools offer incredibly versatile and engaging dialogue capabilities.",

  'AI Security': "Protect your digital assets and proactively defend against threats with AI security tools. As cyber threats become more sophisticated, static defense mechanisms are no longer enough. AI cybersecurity platforms use machine learning to analyze network traffic in real-time, detecting anomalies and zero-day vulnerabilities before they can be exploited. Whether you are securing enterprise endpoints, automating penetration testing, or monitoring for phishing attacks, AI provides a dynamic, self-learning shield that adapts to new threats instantly. Fortify your digital infrastructure with intelligent defense.",

  'AI Data Extraction': "Turn the chaotic web into structured, actionable data with AI data extraction tools. Gathering competitive intelligence or aggregating market data used to require complex web scrapers and constant maintenance. AI data extraction platforms can intelligently navigate websites, understand page layouts visually, and pull specific data points into neat CSVs or APIs without rigid coding. Whether you are tracking real estate listings, monitoring competitor pricing, or building a custom database, AI simplifies web scraping into a seamless, automated process.",

  'AI Presentation': "Captivate your audience and build beautiful slide decks instantly with AI presentation tools. Staring at a blank slide is a thing of the past. AI presentation makers can generate entire outlines, draft speaker notes, and apply professional design templates based on a single topic prompt. Whether you are pitching a startup to investors, delivering a quarterly business review, or teaching a seminar, these platforms help you craft a compelling narrative visually and textually. Save hours of formatting and focus on your delivery.",

  'AI Social Media': "Dominate your social channels and engage your audience effortlessly with AI social media tools. Maintaining a consistent, high-quality social media presence is a full-time job, but AI acts as your dedicated digital agency. From generating viral tweet threads and drafting engaging LinkedIn posts to identifying optimal posting times and analyzing audience sentiment, AI platforms streamline social media management. Whether you are building a personal brand or managing enterprise social accounts, these tools ensure your content strategy is always on point and data-driven.",

  'AI Voice': "Generate incredibly lifelike, expressive audio with AI voice tools. The robotic, monotone text-to-speech engines of the past have been replaced by advanced neural voices that capture human emotion, pacing, and breath. Whether you are narrating an audiobook, producing a podcast, creating localized voiceovers for YouTube videos, or building an interactive voice response (IVR) system, AI voice platforms offer thousands of ultra-realistic voices across dozens of languages. You can even clone your own voice to generate content at scale without stepping into a recording booth.",

  'AI Search': "Find exactly what you are looking for instantly with AI search tools. Traditional keyword search relies on exact matches, often returning irrelevant results. AI semantic search understands the actual intent and meaning behind your queries, scanning massive internal databases, intranets, or the public web to deliver highly accurate, synthesized answers. Whether you are building a knowledge base for your employees or integrating an advanced search bar into your e-commerce site, AI search ensures your users find the needle in the digital haystack every single time.",

  'AI Travel': "Discover the world your way with AI travel tools, where every trip is tailored to your unique tastes and dreams. In the age of personalization, travel is no longer about one-size-fits-all itineraries. It's about crafting your story with journeys that echo your interests, passions, and whims. AI technology is the compass that guides this new era of exploration, analyzing vast data to suggest destinations, accommodations, and activities that align with what you love most. Whether you're an adventure seeker, a culture enthusiast, or someone who relishes the joy of discovery, AI travel tools ensure your experiences are as individual as you are. Embrace a world of travel possibilities designed just for you, where every trip is an opportunity to explore, enjoy, and enrich your life. Set sail on a personalized adventure and let AI be your guide to a world of tailored travel experiences."
};
